pipeline{
    agent any
    stages{
        stage ('Newman tests'){
            steps {
            sh '''
            cd api/newman
            newman run ExamenNewMan.postman_collection.json -e HostExmane.postman_environment.json
            '''
           }
        
        }

        stage ('Jmeter tests'){
            steps {
            sh '''
            cd load/examen_TestPlan.jmx
            export PATH=/home/pjcalvov/jmeter/apache-jmeter-5.3/bin:$PATH
            jmeter -n -t examen_TestPlan.jmx
            '''
           }
        
        }

        stage ('RestAssure tests'){
            steps {
            sh '''
            cd api/restassure
            mvn clean test
            '''
           }
        
        }

        
    }
    
}