pipeline{
    agent any
    stages{
        stage ('Newman tests'){}
        steps {
            sh '''
            cd api/newman
            newman run ExamenNewMan.postman_collection.json -e 
            HostExmane.postman_environment.json
            '''
        }
    }
    
}